language: java
addons:
  sonarcloud:
    organization: "aeris170"
    token:
      secure: "JiudeF2xC5qqDEpbRenyfDa9b6j3EoBByQtnUE6f8dWattAO/nWWVUYubvrucMsCEVNe7XbbS2N3o0X72mX3ZSd4Mlxds827NlfK12i66R5Zlhx+v+bxy5hqPMeaBsQGrovMh9xUBP7uda5MlIg28eXuFi9lQLPLZAxot12D7C69qJlFJbXN8l6SikBsfWogFAnuwn9DCGaQoR1L9Nf/6gUXAIFN8Wc0vMshwHDdq27VsI7vTvxzaHRXV2HAQGkPLNGSjpnqwda161soz1sZBCE33ZBnErL7yab7y0qItW+gGVocWOkknlPt9JfUvDoiDDK8wNDAS6rouHMwic6IbatG3fhEMgx0+SRrmkM1fTU2j5x6OB44s7YEufkmqHogRXmC4P8UqEGn7gZL8681IrOo7UrWknun/GvaDEsOnCs5GnhyAm68Yndv+L9TvdQ6EmBTjZC+rGqn1a/feMKPN0797zLfiFsZ/BOBEh5NJRHhg+LSIO4mu8E7Gu2avIHJFc9DiNieG/scJYkMK0wS8EC9szUSlzqMnSZzKd/af4GeM9gyrx3jEDvp8G9tPR7W6gfsb6qLWrWGRrwhlsdyA74+NaaazLG5pw5Aj5vPY+mkeLJJS6KjHHHW/0j7UyitMrIWVE+t9b+aQU+SA2Kgo8SFrANVAIDorAc87Y9oqbc="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=aeris170_DoaEngine

jdk:
  - openjdk15